// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./../components/App.vue')['default']
    Home: typeof import('./../components/views/Home.vue')['default']
    TuneMic: typeof import('./../components/audio/TuneMic.vue')['default']
  }
}

export { }
