// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('C:/Users/subzt/Code/baby-monitor/src/components/App.vue')['default']
    Home: typeof import('C:/Users/subzt/Code/baby-monitor/src/components/views/Home.vue')['default']
  }
}

export { }
